// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDo2utbFJ2y_O0Xnd_tV_TgyiNhpmoSfRc',
    appId: '1:899885306576:web:95546a7eb5db14a7f304d5',
    messagingSenderId: '899885306576',
    projectId: 'e-dialysis-d9c02',
    authDomain: 'e-dialysis-d9c02.firebaseapp.com',
    storageBucket: 'e-dialysis-d9c02.appspot.com',
    measurementId: 'G-SV7FJCM8RX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeHXF73y2DOeR4LTiiPMIlvh7FCI4ABgE',
    appId: '1:899885306576:android:1b1402d6d4ccfac4f304d5',
    messagingSenderId: '899885306576',
    projectId: 'e-dialysis-d9c02',
    storageBucket: 'e-dialysis-d9c02.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCL0xPljlMWUDlJ94F1WJwsMqw4ORwkBKU',
    appId: '1:899885306576:ios:1964b982938bbd4ff304d5',
    messagingSenderId: '899885306576',
    projectId: 'e-dialysis-d9c02',
    storageBucket: 'e-dialysis-d9c02.appspot.com',
    iosBundleId: 'com.example.edialysis',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCL0xPljlMWUDlJ94F1WJwsMqw4ORwkBKU',
    appId: '1:899885306576:ios:dfb9e27bde94f1c5f304d5',
    messagingSenderId: '899885306576',
    projectId: 'e-dialysis-d9c02',
    storageBucket: 'e-dialysis-d9c02.appspot.com',
    iosBundleId: 'com.example.edialysis.RunnerTests',
  );
}
